java_library(
    name = "app-lib",
    srcs = glob(["*.java"]),
    visibility = ["//src/main/java/com/bmuschko/app:__pkg__"],
    runtime_deps = [
        "//src/main/resources:app-resources"
    ]
)