java_library(
    name = "app-config-lib",
    srcs = glob(["*.java"]),
    deps = [
        "@maven//:org_apache_commons_commons_configuration2"
    ],
    runtime_deps = [
        "@maven//:commons_beanutils_commons_beanutils"
    ]
)