name: Build Exercises
on: [push, pull_request]

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v3
      - name: Exercise 1 - Hello World
        working-directory: exercises/01-hello-world/solution
        run: bazel build //...
      - name: Exercise 2 - Java Binary
        working-directory: exercises/02-java-binary/solution
        run: bazel build //...
      - name: Exercise 4 - Java Package Dependency
        working-directory: exercises/04-java-package-dependency/solution
        run: bazel build //...
      - name: Exercise 5 - Java External Dependency
        working-directory: exercises/05-java-external-dependency/solution
        run: bazel build //...
      - name: Exercise 6 - Java Test
        working-directory: exercises/06-java-test/solution
        run: bazel build //...
      - name: Exercise 7 - Java Library Publish
        working-directory: exercises/07-java-library-publish/solution
        run: bazel build //...
      - name: Exercise 8 - Genrule
        working-directory: exercises/08-genrule/solution
        run: bazel build //:zip-txt-files
